const express = require('express');
const cors = require('cors');
const app = express();
const PORT = process.env.PORT || 3000;
app.use(cors());
app.use(express.json());
app.use((req, res, next) => { console.log(`[${new Date().toLocaleTimeString('es-AR')}] ${req.method} ${req.url}`); next(); });
const pricesRouter = require('./routes/prices');
app.use('/api/prices', pricesRouter);
app.get('/', (req, res) => res.json({ status: 'OK', message: '🚀 Plataforma Inversión IA - Oscar' }));
app.get('/health', (req, res) => res.json({ status: 'healthy', timestamp: new Date().toISOString() }));
app.listen(PORT, () => { console.log(`\n✅ Servidor en http://localhost:${PORT}\n`); });
